GOOSE_MODE: auto
GOOSE_TELEMETRY_ENABLED: false

extensions:
  developer:
    enabled: true
    timeout: 600
  todo:
    enabled: true
  summon:
    enabled: true
  memory:
    enabled: true
  apps:
    enabled: false
  extensionmanager:
    enabled: false
  tom:
    enabled: false
  chatrecall:
    enabled: false
  container-use:
    name: container-use
    cmd: container-use
    args:
      - stdio
    type: stdio
    enabled: true
    timeout: 600
    envs:
      DOCKER_HOST: "unix:///run/user/18626/podman/podman.sock"
