font_family      JetBrains Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        10.0

# If you use ligatures (common in Open Source dev)
disable_ligatures never

enable_audio_bell no
